name: Release VSCode Extension

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          submodules: 'true'

      - name: Install jq
        run: sudo apt-get install jq

      - name: Extract version number
        id: extract-version
        run: |
          version=$(jq -r '.version' package.json)
          echo "Version number: $version"
          echo "VERSION_NUMBER=$version" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install vsce
        run: npm install vsce -g

      - name: Build groovy-language-server
        run: yarn run build-server

      - name: Build vscode extension
        run: yarn run build-extension ${{ env.VERSION_NUMBER }}

      # - name: Upload groovy-language-server
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: bin/groovy-language-server-all.jar
      #     overwrite: true

      # - name: Upload extension
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: groovy-guru-${{needs.tag.outputs.tag}}.vsix
      #     tag: ${{needs.tag.outputs.tag}}
      #     overwrite: true

      - name: Publish Extension
        run: yarn run publish easy-groovy-${{env.VERSION_NUMBER}}.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish Extension to OVSX
        run: yarn run ovsx publish easy-groovy-${{env.VERSION_NUMBER}}.vsix -p ${{ secrets.OVSX_PAT }}
